# @IgnoreInspection BashAddShebang
#
# Homebrew bundle
# @see https://github.com/Homebrew/homebrew-bundle

cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'caskroom/fonts'
#tap 'homebrew/apache'
#tap 'homebrew/bundle'
tap 'homebrew/core'
#tap 'homebrew/dupes'
#tap 'homebrew/php'
tap 'homebrew/services'
#tap 'homebrew/versions'
#tap 'buo/cask-upgrade'

#brew 'ack'
#brew 'ant'
#brew 'apr-util'
#brew 'apr'
#brew 'autoconf'
#brew 'autojump'
#brew 'dnsmasq', service_restart: true
#brew 'freetype'
#brew 'gettext'
brew 'git-extras'
brew 'git'
brew 'gnu-tar'
#brew 'go'
#brew 'httpd', args: ['with-mpm-event']
#brew 'icu4c'
#brew 'imagemagick'
#brew 'jpeg'
#brew 'libpng'
#brew 'libtiff'
#brew 'libtool'
#brew 'libxml2'
#brew 'makedepend'
#brew 'maven'
brew 'mas'
#brew 'mysql', service_restart: true
brew 'node'
#brew 'openssl'
#brew 'pcre'
#brew 'pkg-config'
#brew 'readline'
#brew 'ripgrep'
#brew 'tig'
#brew 'unixodbc'
#brew 'unrar'
#brew 'xz'
brew 'z'
#brew 'zlib'
#brew 'zsh-completions'
#brew 'watchman'

#brew 'homebrew/php/composer'
#brew 'homebrew/php/php70'
#brew 'homebrew/php/php70-apcu'
#brew 'homebrew/php/php70-apcu-bc'
#brew 'homebrew/php/php70-imagick', args: ['build-from-source']
#brew 'homebrew/php/php70-intl'
#brew 'homebrew/php/php70-opcache'
#brew 'homebrew/php/php70-xdebug'

#cask '1password'
#cask 'alfred'
#cask 'atom'
#cask 'betterzip'
#cask 'cleanmymac'
#cask 'colorpicker-skalacolor'
#cask 'dash'
#cask 'default-folder-x'
#cask 'divvy'
#cask 'dropbox'
#cask 'dropshare'
#cask 'evernote'
#cask 'fantastical'
#cask 'firefox'
#cask 'flux'
#cask 'google-chrome'
#cask 'harvest'
#cask 'hazel'
#cask 'istat-menus'
#cask 'iterm2'
#cask 'name-mangler'
#cask 'opera'
#cask 'sequel-pro'
#cask 'sketch'
#cask 'slack'
#cask 'sonos'
#cask 'spectacle'
#cask 'spillo'
#cask 'spotify'
#cask 'transmission'
#cask 'typinator'
#cask 'virtualbox'
#cask 'vlc'
#cask 'wkhtmltopdf'

# Fonts
cask 'font-fira-code'
cask 'font-inconsolata'
cask 'font-fira-mono-for-powerline'
cask 'font-menlo-for-powerline'
cask 'font-meslo-for-powerline'

