# Homebrew bundle
# @see https://github.com/Homebrew/homebrew-bundle

tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'homebrew/apache'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/dupes'
tap 'homebrew/php'
tap 'homebrew/services'
tap 'homebrew/versions'

brew 'apr'
brew 'ack'
brew 'pkg-config'
brew 'makedepend'
brew 'openssl'
brew 'mysql', service_restart: true
brew 'unixodbc'
brew 'apr-util'
brew 'autoconf'
brew 'autojump'
brew 'dnsmasq', service_restart: true
brew 'xz'
brew 'libpng'
brew 'freetype'
brew 'gettext'
brew 'pcre'
brew 'git'
brew 'git-extras'
brew 'gnu-tar'
brew 'go'
brew 'icu4c'
brew 'libtool'
brew 'jpeg'
brew 'libtiff'
brew 'imagemagick'
brew 'libxml2'
brew 'mas'
brew 'maven'
brew 'node'
brew 'readline'
brew 'z'
brew 'tig'
brew 'zsh-completions'
brew 'homebrew/dupes/zlib'
brew 'homebrew/apache/httpd24', args: ['with-mpm-event']
brew 'homebrew/apache/mod_fastcgi', args: ['with-homebrew-httpd24']
brew 'homebrew/php/php70'
brew 'homebrew/php/composer'
brew 'homebrew/php/php70-apcu'
brew 'homebrew/php/php70-imagick'
brew 'homebrew/php/php70-opcache'
brew 'homebrew/php/php70-xdebug'

cask '1password'
cask 'alfred'
cask 'atom'
cask 'cleanmymac'
cask 'default-folder-x'
cask 'divvy'
cask 'dropbox'
cask 'dropshare'
cask 'evernote'
cask 'fantastical'
cask 'firefox'
cask 'flux'
cask 'font-anonymous-pro'
cask 'font-camingocode'
cask 'font-fira-code'
cask 'font-inconsolata'
cask 'google-chrome'
cask 'google-drive'
cask 'harvest'
cask 'hazel'
cask 'istat-menus'
cask 'iterm2'
cask 'macupdate-desktop'
cask 'name-mangler'
cask 'opera'
cask 'sequel-pro'
cask 'shiori'
cask 'sketch'
cask 'sketch-toolbox'
cask 'slack'
cask 'spectacle'
cask 'spotify'
cask 'transmission'
cask 'typinator'
cask 'virtualbox'
cask 'vlc'
cask 'wkhtmltopdf'
cask 'betterzip'

mas 'Noizio (1.5)', id: 928871589
mas 'JPEGmini (1.9.9)', id: 498944723
mas 'DiveLogManager (3.4.27)', id: 404897036
mas 'SiteSucker (2.8.4)', id: 442168834
mas 'Dash (3.3.1)', id: 449589707
mas 'Wunderlist (3.4.4)', id: 410628904
mas 'SonicWALL Mobile Connect (4.0.8)', id: 822514576
